// getters
export const GET_CURRENT_QUESTIONARE = 'GET_CURRENT_QUESTIONARE';
export const GET_QUESTIONARE_SUBMITS = 'GET_QUESTIONARE_SUBMITS';
export const QUESTIONARE_SUBMITS_EXIST = 'QUESTIONARE_SUBMITS_EXIST';

// actions
export const LOAD_QUESTIONARE = 'LOAD_QUESTIONARE';
export const POST_QUESTIONARE = 'POST_QUESTIONARE';
export const RECEIVE_QUESTIONARE = 'RECEIVE_QUESTIONARE';
export const LOAD_QUESTIONARE_SUBMITS = 'LOAD_QUESTIONARE_SUBMITS';

// mutations
export const MODIFY_CURRENT_QUESTIONNAIRE = 'MODIFY_CURRENT_QUESTIONARE';
export const MODIFY_QUESTIONARE_SUBMITS = 'MODIFY_QUESTIONARE_SUBMITS';
