// getters
export const GET_CURRENT_QUESTIONARE = 'GET_CURRENT_QUESTIONARE';

// actions
export const LOAD_QUESTIONARE = 'LOAD_QUESTIONARE';
export const POST_QUESTIONARE = 'POST_QUESTIONARE';

// mutations
export const MODIFY_CURRENT_QUESTIONNAIRE = 'MODIFY_CURRENT_QUESTIONARE';
