// getters
export const GET_PUBLIC_REQUESTS = 'GET_PUBLIC_REQUESTS';
export const GET_SELF_REQUESTS_SENT = 'GET_SELF_REQUESTS_SENT';
export const GET_SELF_REQUESTS_RECEIVED = 'GET_SELF_REQUESTS_RECEIVED';
export const GET_SELF_REQUESTS_DONE = 'GET_SELF_REQUESTS_DONE';
export const GET_SELF_REQUESTS_DRAFT = 'GET_SELF_REQUESTS_DRAFT';

// actions
export const LOAD_REQUESTS = 'LOAD_REQUESTS';
export const POST_REQUESTS = 'POST_REQUESTS';

// mutations
export const SET_REQUESTS = 'SET_REQUESTS';
