// getters
export const GET_ALL_ASSIGNMENTS = 'GET_ALL_ASSIGNMENTS';

// mutations
export const MODIFY_ALL_ASSIGNMENTS = 'MODIFY_ALL_ASSIGNMENTS';

// actions
export const LOAD_ALL_ASSIGNMENTS = 'LOAD_ALL_ASSIGNMENTS';
export const SUBMIT_ASSIGNMENT_ANSWER = 'SUBMIT_ASSIGNMENT_ANSWER';
